[package]
name = "starkdate"
version = "0.1.0"
edition = "2024_07"


[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.19.0" }

[[target.starknet-contract]]
sierra =true
casm = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.33.0" }

[scripts]
test= "snforge test"
